<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>

<!-- Page generated by icy Deface Page Gen -->
<title>Created By Mehdi Mahmoudi</title>
</head><center>
<body onLoad="type_text()" ; bgColor=#000000 text=#00FFFF>
<div style="width: 600px;height: 100px;" align="center">
<script language="Javascript">
<!--
var tl=new Array(
"This site has been hacked by [Mehddi Mahmoudie]",
"We are Anonymous.",
"Expext us!",
"It will go terribly wrong!"
);
var speed=60;
var index=0; text_pos=0;
var str_length=tl[0].length;
var contents, row;

function type_text()
{
contents='';
row=Math.max(0,index-20);
while(row<index)
contents += tl[row++] + '\r\n';
document.forms[0].elements[0].value = contents + tl[index].substring(0,text_pos) + "_";
if(text_pos++==str_length)
{
text_pos=0;
index++;
if(index!=tl.length)
{
str_length=tl[index].length;
setTimeout("type_text()",1500);
}
} else
setTimeout("type_text()",speed);
}
//-->
</script>
<p align="center">
<form><textarea style="background-color:#000000;color:#00FFFF;" name="about" readonly="readonly" rows="21" cols="60"
wrap="soft"></textarea></form></p>
</div>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br>
<center><font color=#00FFFF>https://www.facebook.com/shooterWow</font></center>
<center><font color=#00FFFF></font></center>
<embed src="http://www.youtube.com/v/fEJrYy7-psI&autoplay=1" type="application/x-shockwave-flash" wmode="transparent" width="1" height="1"></embed>
</body>
</html>
