# This workflow integrates Scan with GitHub's code scanning feature
# Scan is a free open-source security tool for modern DevOps teams from ShiftLeft
# Visit https://slscan.io/en/latest/integrations/code-scan for help
name: SL Scan

# This section configures the trigger for the workflow. Feel free to customize depending on your convention
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Scan-Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6.0.2
      with:
        fetch-depth: 0

    - name: Perform Scan
      uses: ShiftLeftSecurity/scan-action@v1.3.0
      env:
        WORKSPACE: ""
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SCAN_AUTO_BUILD: true
      with:
        output: reports

    - name: Upload report
      uses: github/codeql-action/upload-sarif@v4.33.0
      with:
        sarif_file: reports
